# Invariant polynomial bases (PLAN §6 Tier 3, first decision).
#
# Choice: the invariant subspace is computed, not hard-coded as formulas, but it is pinned
# to a hard-coded dimension count. For each degree k the orthonormal basis block V_k (the
# degree-k orthogonal complement) is a representation of the symmetry group, and because the
# measure is invariant the Reynolds operator R = |G|⁻¹ Σ_g g* maps V_k to itself as an
# orthogonal projector. Its range, extracted by pivoted Gram–Schmidt, is the degree-k part
# of the invariant ring; its dimension must equal the Molien coefficient, which is checked
# on every computation, not just in tests.
#
# For S_{D+1} on the D-simplex the invariant ring is generated by the power sums of the
# centred barycentric coordinates of degree 2, …, D+1, so the Molien series is
# Π_{j=2}^{D+1} 1/(1 - t^j).
#
# The basis Q is computed in Float64 on purpose. For a symmetric rule the full residual
# vector r lies exactly in the invariant subspace S (up to working-precision rounding), and
# any Q' close to an orthonormal basis of S makes Q'ᵀ: S → ℝᵐ invertible. So Q'ᵀ r = 0
# has exactly the solution set of r = 0: the accuracy of Q affects conditioning, never the
# converged rule. All arithmetic here is plain loops (no BLAS), so Q is bitwise identical on
# every platform.

"""
    molien_coefficient(N, k)

Dimension of the degree-`k` part of the invariant ring of `S_N` acting on the
`(N-1)`-simplex: the number of partitions of `k` into parts from `{2, …, N}`.
"""
function molien_coefficient(N::Integer, k::Integer)
    k < 0 && return 0
    c = zeros(Int, k + 1)
    c[1] = 1
    for part in 2:N, j in part:k
        c[j + 1] += c[j - part + 1]
    end
    return c[k + 1]
end

"Number of invariant equations for exactness up to total degree `n`."
n_invariants(N::Integer, n::Integer) = sum(k -> molien_coefficient(N, k), 0:n)

"""
    InvariantBasis

Orthonormal basis of the `S_3`-invariant polynomials of degree `≤ n` on the reference
triangle, as a matrix `Q` whose columns are coefficient vectors in the orthonormal Dubiner
basis. `ranks[k+1]` is the dimension found at degree `k`.
"""
struct InvariantBasis
    n::Int
    Q::Matrix{Float64}
    ranks::Vector{Int}
end

"""
    invariant_basis(N, n)

The invariant basis for `S_N` on the `(N-1)`-simplex up to degree `n`. Implemented for
the triangle (`N = 3`); the tetrahedron arrives with its orthonormal basis in v0.2.
"""
function invariant_basis(N::Integer, n::Integer)
    N == 3 || throw(NotYetImplemented("invariant bases for S_$N", "v0.2"))
    # a quadrature rule exact to degree 2n, in Float64, for the Reynolds projector
    X, W, _, _ = conical_work(2, n + 1, 53 + 64)
    xs = [(Float64(x[1]), Float64(x[2])) for x in X]
    ws = [Float64(w) for w in W]
    L = dubiner_length(n)
    ws_ = DubinerWorkspace{Float64}(n)
    φ = zeros(L)
    Rφ = zeros(L)
    perms = permutations_of(3)
    M = zeros(L, L)               # only the diagonal blocks are filled
    for (q, (x, y)) in enumerate(xs)
        λ = (1 - x - y, x, y)
        fill!(Rφ, 0.0)
        for σ in perms
            dubiner!(φ, ws_, λ[σ[2]], λ[σ[3]])
            for i in 1:L
                Rφ[i] += φ[i]
            end
        end
        for i in 1:L
            Rφ[i] /= length(perms)
        end
        dubiner!(φ, ws_, x, y)
        for k in 0:n
            r = (dubiner_index(0, k)):(dubiner_index(k, 0))
            for i in r, j in r
                M[i, j] += ws[q] * φ[i] * Rφ[j]
            end
        end
    end
    cols = Vector{Vector{Float64}}()
    ranks = Int[]
    for k in 0:n
        r = (dubiner_index(0, k)):(dubiner_index(k, 0))
        block = [M[r, j] for j in r]
        basis = pivoted_gram_schmidt!(block, 1e-8)
        expected = molien_coefficient(N, k)
        length(basis) == expected ||
            error("invariant basis at degree $k has dimension $(length(basis)); Molien predicts $expected")
        push!(ranks, length(basis))
        for v in basis
            full = zeros(L)
            full[r] .= v
            push!(cols, full)
        end
    end
    Q = reduce(hcat, cols)
    return InvariantBasis(Int(n), Q, ranks)
end

# Pivoted modified Gram–Schmidt with reorthogonalisation. Columns are consumed. The
# tolerance is absolute: the Reynolds block is an orthogonal projector (eigenvalues 0 or 1),
# so there is no scale to be relative to.
function pivoted_gram_schmidt!(cols::Vector{Vector{Float64}}, tol::Float64)
    out = Vector{Vector{Float64}}()
    remaining = copy(cols)
    while !isempty(remaining)
        norms = map(_norm2, remaining)
        j = argmax(norms)
        norms[j] <= tol && break
        v = remaining[j] ./ norms[j]
        deleteat!(remaining, j)
        for pass in 1:2, u in remaining
            c = _dot(v, u)
            for i in eachindex(u)
                u[i] -= c * v[i]
            end
        end
        push!(out, v)
    end
    return out
end

function _dot(a, b)
    s = 0.0
    for i in eachindex(a)
        s += a[i] * b[i]
    end
    return s
end
_norm2(a) = sqrt(_dot(a, a))
