# Invariant polynomial bases (PLAN §6 Tier 3, first decision).
#
# Choice: the invariant subspace is computed, not hard-coded as formulas, but it is pinned
# to a hard-coded dimension count. For each degree k the orthonormal basis block V_k (the
# degree-k orthogonal complement) is a representation of the symmetry group, and because the
# measure is invariant the Reynolds operator R = |G|⁻¹ Σ_g g* maps V_k to itself as an
# orthogonal projector. Its range, extracted by pivoted Gram–Schmidt, is the degree-k part
# of the invariant ring; its dimension must equal the Molien coefficient, which is checked
# on every computation, not just in tests.
#
# For S_{D+1} on the D-simplex the invariant ring is generated by the power sums of the
# centred barycentric coordinates of degree 2, …, D+1, so the Molien series is
# Π_{j=2}^{D+1} 1/(1 - t^j).
#
# The basis Q is computed in Float64 on purpose. For a symmetric rule the full residual
# vector r lies exactly in the invariant subspace S (up to working-precision rounding), and
# any Q' close to an orthonormal basis of S makes Q'ᵀ: S → ℝᵐ invertible. So Q'ᵀ r = 0
# has exactly the solution set of r = 0: the accuracy of Q affects conditioning, never the
# converged rule. All arithmetic here is plain loops (no BLAS), so Q is bitwise identical on
# every platform.

"""
    molien_coefficient(N, k)

Dimension of the degree-`k` part of the invariant ring of `S_N` acting on the
`(N-1)`-simplex: the number of partitions of `k` into parts from `{2, …, N}`.
"""
function molien_coefficient(N::Integer, k::Integer)
    k < 0 && return 0
    c = zeros(Int, k + 1)
    c[1] = 1
    for part in 2:N, j in part:k
        c[j + 1] += c[j - part + 1]
    end
    return c[k + 1]
end

"Number of invariant equations for exactness up to total degree `n`."
n_invariants(N::Integer, n::Integer) = sum(k -> molien_coefficient(N, k), 0:n)

"""
    InvariantBasis

Orthonormal basis of the `S_N`-invariant polynomials of degree `≤ n` on the reference
`(N-1)`-simplex, as a matrix `Q` whose columns are coefficient vectors in the orthonormal
Dubiner basis of that simplex. `ranks[k+1]` is the dimension found at degree `k`.
"""
struct InvariantBasis
    N::Int
    n::Int
    Q::Matrix{Float64}
    ranks::Vector{Int}
end

"""
    invariant_basis(N, n)

The invariant basis for `S_N` on the `(N-1)`-simplex up to degree `n`, for the triangle
(`N = 3`) and the tetrahedron (`N = 4`). The dimension of every degree block is checked
against the Molien series; a mismatch is an error, not a warning.
"""
function invariant_basis(N::Integer, n::Integer)
    D = N - 1
    D in (2, 3) || throw(NotYetImplemented("invariant bases for S_$N", "a later release"))
    # a quadrature rule exact to degree 2n, in Float64, for the Reynolds projector
    X, W, _, _ = conical_work(D, n + 1, 53 + 64)
    xs = [Float64.(x) for x in X]
    ws = Float64.(W)
    basis = SimplexBasis{D,Float64}(n)
    blocks = degree_blocks(basis)
    Mb = reynolds_blocks(basis, N, xs, ws, blocks)
    L = basis_length(basis)
    cols = Vector{Vector{Float64}}()
    ranks = Int[]
    for (k, r) in zip(0:n, blocks)
        M = Mb[k + 1]
        found = pivoted_gram_schmidt!([M[:, j] for j in axes(M, 2)], 1e-8)
        expected = molien_coefficient(N, k)
        length(found) == expected ||
            error("invariant basis at degree $k has dimension $(length(found)); Molien predicts $expected")
        push!(ranks, length(found))
        for v in found
            full = zeros(L)
            full[r] .= v
            push!(cols, full)
        end
    end
    return InvariantBasis(Int(N), Int(n), reduce(hcat, cols), ranks)
end


"Blocks of the Reynolds projector ∫ φᵢ (Rφⱼ), by quadrature (behind a function barrier)."
function reynolds_blocks(basis::SimplexBasis{D}, N, xs, ws, blocks) where {D}
    L = basis_length(basis)
    Mb = [zeros(length(r), length(r)) for r in blocks]
    φ0 = zeros(L)
    Rφ = zeros(L)
    perms = permutations_of(N)
    λ = zeros(N)
    for (q, x) in enumerate(xs)
        λ[1] = 1 - sum(x)
        λ[2:end] .= x
        fill!(Rφ, 0.0)
        for σ in perms
            φ, _ = evaluate!(basis, [λ[σ[j + 1]] for j in 1:D]; gradient = false)
            for i in 1:L
                Rφ[i] += φ[i]
            end
        end
        for i in 1:L
            Rφ[i] /= length(perms)
        end
        φ, _ = evaluate!(basis, x; gradient = false)
        copyto!(φ0, φ)
        for (b, r) in enumerate(blocks)
            M = Mb[b]
            o = first(r) - 1
            for j in r, i in r
                M[i - o, j - o] += ws[q] * φ0[i] * Rφ[j]
            end
        end
    end
    return Mb
end

# Pivoted modified Gram–Schmidt with reorthogonalisation. Columns are consumed. The
# tolerance is absolute: the Reynolds block is an orthogonal projector (eigenvalues 0 or 1),
# so there is no scale to be relative to.
function pivoted_gram_schmidt!(cols::Vector{Vector{Float64}}, tol::Float64)
    out = Vector{Vector{Float64}}()
    remaining = copy(cols)
    while !isempty(remaining)
        norms = map(_norm2, remaining)
        j = argmax(norms)
        norms[j] <= tol && break
        v = remaining[j] ./ norms[j]
        deleteat!(remaining, j)
        for pass in 1:2, u in remaining
            c = _dot(v, u)
            for i in eachindex(u)
                u[i] -= c * v[i]
            end
        end
        push!(out, v)
    end
    return out
end

function _dot(a, b)
    s = 0.0
    for i in eachindex(a)
        s += a[i] * b[i]
    end
    return s
end
_norm2(a) = sqrt(_dot(a, a))
