# Generate the MIT-licensed seed table for fully symmetric tetrahedron rules,
# src/data/tetrahedron_s4_seeds.toml, from orbit structures alone (PLAN §0.2).
#
#     julia --project -t auto scripts/generate_tetrahedron_seeds.jl [mindegree] maxdegree
#
# No published point counts are relied on. For each degree the search starts at a point
# count no larger than any fully symmetric rule could have (the smallest count whose
# structures have as many unknowns as S₄-invariant equations, or the previous degree's
# count, whichever is larger) and walks upwards. At each count a few structures are tried,
# those whose mix of orbit types is closest to the previous degree's rule first (the
# structure evolves smoothly with degree), then those with the fewest unknowns. They are
# tried by multistart Levenberg–Marquardt; the first count with a valid rule (positive
# weights, interior nodes) wins, and among its rules the one with the largest minimum
# barycentric coordinate is kept. The count found is therefore the smallest this
# search reached, not a proven minimum. Entries are rewritten after every degree.

isdefined(Main, :CR) || (import CubatureRules; const CR = CubatureRules)
using LinearAlgebra, Printf, TOML
BLAS.set_num_threads(1)

const STRUCTURES_PER_COUNT = 6
const MAX_WALK = 40
const TYPES = sort(CR.orbit_pattern_types(4); by = p -> (-length(p.mult), p.mult))

"Number of orbits of each pattern type, in canonical type order."
type_counts(s) = [count(o -> o.mult == t.mult, s.orbits) for t in TYPES]

"Smallest point count with a structure having at least `m` unknowns."
function lower_count(n)
    npts = 1
    while isempty(CR.candidate_structures(npts, n, 4))
        npts += 1
    end
    return npts
end

function search(n, start, prevcounts; nstarts)
    basis = CR.invariant_basis(4, n)
    m = size(basis.Q, 2)
    for npts in start:(start + MAX_WALK)
        ss = CR.candidate_structures(npts, n, 4; max_unknowns = m + 3)
        prevcounts === nothing ||
            sort!(ss; by = s -> (sum(abs, type_counts(s) .- prevcounts), CR.nunknowns(s)))  # stable
        for s in first(ss, STRUCTURES_PER_COUNT)
            t = @elapsed found = CR.multistart(s, n; nstarts, basis, first_only = false)
            @printf("    degree %d, %d points, %d unknowns (%d equations): %d valid in %.0f s\n",
                    n, npts, CR.nunknowns(s), m, length(found), t)
            flush(stdout)
            isempty(found) && continue
            return s, argmax(f -> (f[3], -f[4]), found), length(found), basis
        end
    end
    return nothing
end

function main(mindeg, maxdeg, path)
    entries = isfile(path) ? filter(e -> !(mindeg <= e["degree"] <= maxdeg), TOML.parsefile(path)["rule"]) :
              Dict{String,Any}[]
    done = sort(filter(e -> e["degree"] < mindeg && e["status"] == "ok", entries); by = e -> e["degree"])
    prev = isempty(done) ? 1 : last(done)["npoints"]
    prevcounts = isempty(done) ? nothing :
                 type_counts(CR.SymmetricStructure([Int.(m) for m in last(done)["structure"]], 4))
    for n in mindeg:maxdeg
        start = max(lower_count(n), prev)
        nstarts = n <= 8 ? 512 : 1024
        t = @elapsed found = search(n, start, prevcounts; nstarts)
        if found === nothing
            @printf("degree %2d: no rule found from %d to %d points\n", n, start, start + MAX_WALK)
            push!(entries, Dict("degree" => n, "npoints" => 0, "structure" => Vector{Int}[], "seed" => Float64[],
                                "status" => "failed", "note" => "no valid rule found in the searched range"))
            write_table(path, entries)
            continue
        end
        s, best, nfound, basis = found
        θ, res, _ = CR.refine_symmetric(s, n, best[1], CR.digits_to_bits(100); basis)
        res.converged || error("degree $n: refinement to 100 digits failed")
        θ64 = Float64.(θ)
        wmin, λmin = CR.rule_margins(s, θ64)
        @printf("degree %2d: %3d pts  %d unknowns  %d valid  cond %.1e  iters %d  (%.1f s)\n",
                n, CR.npoints(s), CR.nunknowns(s), nfound, res.cond, res.iterations, t)
        flush(stdout)
        prev = CR.npoints(s)
        prevcounts = type_counts(s)
        push!(entries, Dict("degree" => n, "npoints" => CR.npoints(s), "search_start" => start,
                            "structure" => [o.mult for o in s.orbits], "seed" => θ64,
                            "status" => "ok", "note" => "", "valid_rules_found" => nfound,
                            "min_weight" => wmin, "min_barycentric" => λmin, "cond" => res.cond))
        write_table(path, entries)
    end
    return entries
end

function write_table(path, entries)
    open(path, "w") do io
        println(io, "# Fully symmetric (S₄) tetrahedron rule seeds for CubatureRules.jl — MIT licence.")
        println(io, "# Generated by scripts/generate_tetrahedron_seeds.jl from orbit structures alone;")
        println(io, "# no numbers or point counts were taken from any published table. See PROVENANCE.toml.")
        println(io, "#")
        println(io, "# seed layout: per orbit, [weight per point, free barycentric values...].")
        println(io)
        TOML.print(io, Dict("rule" => sort(entries; by = e -> e["degree"])); sorted = true)
    end
end

if abspath(PROGRAM_FILE) == @__FILE__
    lo, hi = length(ARGS) == 2 ? Tuple(parse.(Int, ARGS)) : (1, isempty(ARGS) ? 10 : parse(Int, ARGS[1]))
    main(lo, hi, joinpath(@__DIR__, "..", "src", "data", "tetrahedron_s4_seeds.toml"))
end
