# Generate the MIT-licensed seed table for fully symmetric triangle rules,
# src/data/triangle_s3_seeds.toml, from orbit structures alone (PLAN §0.2).
#
#     julia --project -t auto scripts/generate_triangle_seeds.jl [maxdegree]
#
# For each degree the target point count is the minimal count reported by Xiao & Gimbutas
# (2010) — a combinatorial fact stated in the paper, not tabulated data. Every orbit
# structure with that many points and at least as many unknowns as S₃-invariant equations
# is searched by multistart Levenberg–Marquardt; the first structure (fewest unknowns) with
# a valid rule wins, and among its valid rules the one with the largest minimum barycentric
# coordinate is kept. The Float64 seed written out is the 100-digit refinement rounded to
# Float64. If no structure at the target count yields a rule, the count is increased and the
# entry says so.

isdefined(Main, :CR) || (import CubatureRules; const CR = CubatureRules)
using LinearAlgebra, Printf, TOML
BLAS.set_num_threads(1)

# Minimal point counts, Xiao & Gimbutas (2010), Table 6.1 (triangle), degrees 1–20.
const XG_POINTS = [1, 3, 6, 6, 7, 12, 15, 16, 19, 25, 28, 33, 37, 42, 49, 55, 60, 67, 73, 79]

function search(n, npts; nstarts)
    basis = CR.invariant_basis(3, n)
    for extra in 0:3, s in CR.candidate_structures(npts + extra, n)
        found = CR.multistart(s, n; nstarts, basis, first_only = false)
        isempty(found) && continue
        best = argmax(t -> (t[3], -t[4]), found)
        return s, best, length(found), extra, basis
    end
    return nothing
end

function main(maxdeg)
    entries = Dict{String,Any}[]
    for n in 1:maxdeg
        npts = XG_POINTS[n]
        nstarts = n <= 10 ? 512 : n <= 15 ? 1024 : 2048
        t = @elapsed found = search(n, npts; nstarts)
        if found === nothing
            @printf("degree %2d: no rule found near %d points\n", n, npts)
            push!(entries, Dict("degree" => n, "npoints" => npts, "structure" => Vector{Int}[],
                                "seed" => Float64[], "status" => "failed",
                                "note" => "multistart found no valid rule within 3 points of the target"))
            continue
        end
        s, best, nfound, extra, basis = found
        θ, res, guard = CR.refine_symmetric_triangle(s, n, best[1], CR.digits_to_bits(100); basis)
        res.converged || error("degree $n: refinement to 100 digits failed")
        θ64 = Float64.(θ)
        wmin, λmin = CR.rule_margins(s, θ64)
        @printf("degree %2d: %3d pts  %-40s  %d valid  cond %.1e  iters %d  (%.1f s)\n",
                n, CR.npoints(s), string([o.mult for o in s.orbits]), nfound, res.cond, res.iterations, t)
        note = extra == 0 ? "" : "no valid rule at the published count; $(extra) extra point(s)"
        push!(entries, Dict("degree" => n, "npoints" => CR.npoints(s),
                            "structure" => [o.mult for o in s.orbits], "seed" => θ64,
                            "status" => "ok", "note" => note, "valid_rules_found" => nfound,
                            "min_weight" => wmin, "min_barycentric" => λmin, "cond" => res.cond))
    end
    return entries
end

function write_table(path, entries)
    open(path, "w") do io
        println(io, "# Fully symmetric (S₃) triangle rule seeds for CubatureRules.jl — MIT licence.")
        println(io, "# Generated by scripts/generate_triangle_seeds.jl from orbit structures alone;")
        println(io, "# no numbers were taken from any published table. See PROVENANCE.toml.")
        println(io, "#")
        println(io, "# seed layout: per orbit, [weight per point, free barycentric values...].")
        println(io)
        TOML.print(io, Dict("rule" => entries); sorted = true)
    end
end

if abspath(PROGRAM_FILE) == @__FILE__
    maxdeg = isempty(ARGS) ? 20 : parse(Int, ARGS[1])
    entries = main(maxdeg)
    write_table(joinpath(@__DIR__, "..", "src", "data", "triangle_s3_seeds.toml"), entries)
end
